### ISSUE TITLE
Testing needs to get us food

### ISSUE THREAD

**Issue by SHABIAN** [WestwoodCompSci/SkippableTV_15.7#4]
We are unable to work unless we have more food. Testing has nothing to do unless we get stuff done so they should get us food so we can finish.

**Comment by uksangyoo** [comment]
Dear Shabian,
Unfortunately, due to recent budget cuts and implementation of new restrictions by the management, we are unable to provide the "necessary" services that you "need."
Please contact the HR department for other complaints. (email: noah.tinney@gmail.com)
Sincerely,
Uksang Yoo, the acting director of the Testing Department at SKiPpaBLe.TV

**Comment by SHABIAN** [comment]
FOOD OR STRIKE!!!

**Comment by MRTZA** [comment]
We are officially on strike!

**Comment by lekro** [comment]
Networking officially joins the strike.

**Comment by SHABIAN** [comment]
Look what you have caused TESTING!

**Comment by SHABIAN** [comment]
We are officially off strike.
